version: "3.9"

services:
  ibbi-ui:
    container_name: ibbi-ui
    build:
      context: .
      args:
        PORT: ${FRONTEND_PORT}
    restart: always
    env_file: .env
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - api-network

  ibbi-api:
    container_name: ibbi-api
    build:
      context: .
      args:
        - PORT=${CORE_PORT}
    restart: always
    volumes:
      - ./src:/code/src
    env_file: .env
    ports:
      - ${CORE_PORT}:${CORE_PORT}
    depends_on:
      - postgres-db
    networks:
      - api-network

  postgres-db:
    container_name: postgres-db
    image: postgres
    restart: always
    volumes:
      - /var/lib/pgdata:/var/lib/postgresql/data
    env_file: .env
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
